### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by mastazi** [da2x/amp2html#10]
I just found out that amp2html breaks a website, would it be possible to add the option to whitelist domains?

**Comment by da2x** [comment]
Could you please provide the AMP link that breaks so I can have a look at it?

**Comment by selurvedu** [comment]
@da2x is this feature available? I would like to exclude one domain because the actual website is ugly, overloaded with useless junk and full of distractions I'm not interested in, and the AMP version is very simple, clean, lightweight and very Web 1.0-ish in general. Moreover, I'd like to have an automatic "redirect to AMP" feature for that particular site to never see the "normal" version.
